---
- name: Install libcap
  package:
    name: "libcap2-bin"
    state: present
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
...
